### ISSUE TITLE
在hexo-admin-qiniu插件中无法复制粘贴.

### ISSUE THREAD

**Issue by xinuo** [xbotao/hexo-admin-qiniu#1]
在http://ip:4000/admin后台管理中,新增文章时,
拷贝图片或者截图粘贴都无法粘贴图片.
当时已经在_config.yml配置好七牛的配置.

**Comment by xinuo** [comment]
后来经检查,yml配置需要严格的排版格式.
当时错误的配置:
-----------------分割线----------
```
admin:


qiniuCfg:
  AccessKey: '*****'
  SecretKey: '******'
  BucketName: '****'
  bucketHost: '****.bkt.clouddn.com'
```

-----------------分割线----------
后来正确的配置
```
admin:
  qiniuCfg:
    AccessKey: '*****'
    SecretKey: '******'
    BucketName: '****'
    bucketHost: '****.bkt.clouddn.com'
```
现在可以粘贴图片并获取七牛的地址了.
