### ISSUE TITLE
win10下无法复制粘贴

### ISSUE THREAD

**Issue by GeekaholicLin** [xbotao/hexo-admin-qiniu#2]
``` yaml
### 配置文件
admin:
  qiniuCfg:
    AccessKey: '*****'
    SecretKey: '****'
    BucketName: 'blog'
    bucketHost: '***.bkt.clouddn.com'
```

官方插件可以复制粘贴，但是这个插件不可以。应该不关配置的事情，而是在预览界面没有任何内容，不关上传的事
